name: Confluence best practices for Python

on:
  workflow_dispatch: {}          # <-- adds the Run workflow button
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  post-spec:
    runs-on: ubuntu-latest
    env:
      URL: "https://manulife-asia.atlassian.net/wiki/api/v2/pages/776668002?body-format=storage"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure jq is installed
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Confluence JSON
        env:
          CONF_USERNAME: ${{ secrets.CONF_USERNAME }}
          CONF_API: ${{ secrets.CONF_API }}
        run: |
          set -e
          if [ -z "$CONF_USERNAME" ] || [ -z "$CONF_API" ]; then
            echo "Missing CONF_USERNAME / CONF_API secrets"; exit 1
          fi
          curl -s -u "$CONF_USERNAME:$CONF_API" "$URL" -o page.json
          BODY=$(jq -r '.body.storage.value // empty' page.json)
          if [ -z "$BODY" ] || [ "$BODY" = "null" ]; then
            jq . page.json > page.pretty.json
            {
              echo "```json"
              cat page.pretty.json
              echo "```"
            } > BODY.md
          else
            {
              echo "```html"
              printf "%s\n" "$BODY"
              echo "```"
            } > BODY.md
          fi

      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ### 📎 Confluence Specification
            **Source:** [Open in Confluence](https://manulife-asia.atlassian.net/wiki/api/v2/pages/776668002?body-format=storage)

            <details>
            <summary>View fetched content</summary>

            $(cat BODY.md)

            </details>
