name: Confluence best practices for Python

on:
  # Triggers whenever a PR is opened, re-opened, or updated
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read
  checks: write

jobs:
  post-spec:
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.CONF_URL }}
    steps:
      - name: Ensure jq is available
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Confluence JSON
        env:
          CONF_USERNAME: ${{ secrets.CONF_USERNAME }}
          CONF_API: ${{ secrets.CONF_API }}
        run: |
          set -e
          if [ -z "$CONF_USERNAME" ] || [ -z "$CONF_API" ]; then
            echo "Missing CONF_USERNAME / CONF_API secrets"; exit 1
          fi
          curl -s -u "$CONF_USERNAME:$CONF_API" "$URL" -o page.json
          BODY=$(jq -r '.body.storage.value // empty' page.json)
          if [ -z "$BODY" ] || [ "$BODY" = "null" ]; then
            jq . page.json > page.pretty.json
            {
              echo "```json"
              cat page.pretty.json
              echo "```"
            } > BODY.md
          else
            {
              echo "```html"
              printf "%s\n" "$BODY"
              echo "```"
            } > BODY.md
          fi

      - name: Comment on PR with spec
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          # 'identifier' ensures we update our own comment on subsequent syncs
          identifier: confluence-spec-comment
          body: |
            ### 📎 Confluence Specification
            **Source:** [Open in Confluence](https://manulife-asia.atlassian.net/wiki/api/v2/pages/776668002?body-format=storage)

            <details>
            <summary>View fetched content</summary>

            $(cat BODY.md)

            </details>

      - name: Add Checks tab summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('BODY.md', 'utf8');
            const { data: checkRun } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Confluence Spec',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: 'neutral',
              output: {
                title: 'Confluence Specification',
                summary: 'Spec fetched from Confluence. Link below.',
                text: `**Source:** https://manulife-asia.atlassian.net/wiki/api/v2/pages/776668002?body-format=storage\n\n` + body
              }
            });
