name: Confluence best practices for Python

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  post-spec:
    runs-on: ubuntu-latest
    env:
      URL: "https://manulife-asia.atlassian.net/wiki/api/v2/pages/776668002?body-format=storage"
    steps:
      - name: Checkout (needed by some actions)
        uses: actions/checkout@v4

      - name: Fetch Confluence JSON
        env:
          CONF_USERNAME: ${{ secrets.CONF_USERNAME }}
          CONF_API: ${{ secrets.CONF_API }}
        run: |
          set -e
          curl -s -u "$CONF_USERNAME:$CONF_API" "$URL" -o page.json
          # Try to extract the Storage body (HTML-ish) if present; otherwise keep JSON
          if command -v jq >/dev/null 2>&1; then
            BODY=$(jq -r '.body.storage.value // empty' page.json)
            if [ -z "$BODY" ] || [ "$BODY" = "null" ]; then
              # fallback to whole JSON pretty
              jq . page.json > page.pretty.json
              echo "```json" > BODY.md
              cat page.pretty.json >> BODY.md
              echo "```" >> BODY.md
            else
              # Put the storage body inside a code fence so GitHub keeps it readable
              # (GitHub sanitizes HTML in comments; this is mainly for quick reference)
              echo "```html" > BODY.md
              printf "%s\n" "$BODY" >> BODY.md
              echo "```" >> BODY.md
            fi
          else
            echo "jq not found" > BODY.md
          fi

      - name: Create or update PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ### 📎 Confluence Specification
            **Source:** [Open in Confluence](https://manulife-asia.atlassian.net/wiki/api/v2/pages/776668002?body-format=storage)

            <details>
            <summary>View fetched content</summary>

            $(cat BODY.md)

            </details>
